// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommChatResponse.proto

package com.gejian.pixel.proto;

public final class CommChatResponseProtobuf {
  private CommChatResponseProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommChatResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CommChatResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 result = 10;</code>
     */
    int getResult();

    /**
     * <code>.CommChatRequest request = 11;</code>
     */
    boolean hasRequest();
    /**
     * <code>.CommChatRequest request = 11;</code>
     */
    com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest getRequest();
    /**
     * <code>.CommChatRequest request = 11;</code>
     */
    com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequestOrBuilder getRequestOrBuilder();
  }
  /**
   * Protobuf type {@code CommChatResponse}
   */
  public  static final class CommChatResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CommChatResponse)
      CommChatResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommChatResponse.newBuilder() to construct.
    private CommChatResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommChatResponse() {
      result_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommChatResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 80: {

              result_ = input.readUInt32();
              break;
            }
            case 90: {
              com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gejian.pixel.proto.CommChatResponseProtobuf.internal_static_CommChatResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gejian.pixel.proto.CommChatResponseProtobuf.internal_static_CommChatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse.class, com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 10;
    private int result_;
    /**
     * <code>uint32 result = 10;</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int REQUEST_FIELD_NUMBER = 11;
    private com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest request_;
    /**
     * <code>.CommChatRequest request = 11;</code>
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>.CommChatRequest request = 11;</code>
     */
    public com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest getRequest() {
      return request_ == null ? com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest.getDefaultInstance() : request_;
    }
    /**
     * <code>.CommChatRequest request = 11;</code>
     */
    public com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != 0) {
        output.writeUInt32(10, result_);
      }
      if (request_ != null) {
        output.writeMessage(11, getRequest());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, result_);
      }
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, getRequest());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse)) {
        return super.equals(obj);
      }
      com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse other = (com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse) obj;

      boolean result = true;
      result = result && (getResult()
          == other.getResult());
      result = result && (hasRequest() == other.hasRequest());
      if (hasRequest()) {
        result = result && getRequest()
            .equals(other.getRequest());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommChatResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CommChatResponse)
        com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gejian.pixel.proto.CommChatResponseProtobuf.internal_static_CommChatResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gejian.pixel.proto.CommChatResponseProtobuf.internal_static_CommChatResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse.class, com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse.Builder.class);
      }

      // Construct using com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = 0;

        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gejian.pixel.proto.CommChatResponseProtobuf.internal_static_CommChatResponse_descriptor;
      }

      @java.lang.Override
      public com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse getDefaultInstanceForType() {
        return com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse build() {
        com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse buildPartial() {
        com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse result = new com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse(this);
        result.result_ = result_;
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse) {
          return mergeFrom((com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse other) {
        if (other == com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse.getDefaultInstance()) return this;
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int result_ ;
      /**
       * <code>uint32 result = 10;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>uint32 result = 10;</code>
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 result = 10;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest request_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest, com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest.Builder, com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequestOrBuilder> requestBuilder_;
      /**
       * <code>.CommChatRequest request = 11;</code>
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>.CommChatRequest request = 11;</code>
       */
      public com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>.CommChatRequest request = 11;</code>
       */
      public Builder setRequest(com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CommChatRequest request = 11;</code>
       */
      public Builder setRequest(
          com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CommChatRequest request = 11;</code>
       */
      public Builder mergeRequest(com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CommChatRequest request = 11;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CommChatRequest request = 11;</code>
       */
      public com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.CommChatRequest request = 11;</code>
       */
      public com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>.CommChatRequest request = 11;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest, com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest.Builder, com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest, com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequest.Builder, com.gejian.pixel.proto.CommChatRequestProtobuf.CommChatRequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CommChatResponse)
    }

    // @@protoc_insertion_point(class_scope:CommChatResponse)
    private static final com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse();
    }

    public static com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommChatResponse>
        PARSER = new com.google.protobuf.AbstractParser<CommChatResponse>() {
      @java.lang.Override
      public CommChatResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommChatResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommChatResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommChatResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gejian.pixel.proto.CommChatResponseProtobuf.CommChatResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommChatResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommChatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026CommChatResponse.proto\032\025CommChatReques" +
      "t.proto\"E\n\020CommChatResponse\022\016\n\006result\030\n " +
      "\001(\r\022!\n\007request\030\013 \001(\0132\020.CommChatRequestB2" +
      "\n\026com.gejian.pixel.protoB\030CommChatRespon" +
      "seProtobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gejian.pixel.proto.CommChatRequestProtobuf.getDescriptor(),
        }, assigner);
    internal_static_CommChatResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CommChatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommChatResponse_descriptor,
        new java.lang.String[] { "Result", "Request", });
    com.gejian.pixel.proto.CommChatRequestProtobuf.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
