// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommRanklistRelativePowerResponse.proto

package com.gejian.pixel.proto;

public final class CommRanklistRelativePowerResponseProtobuf {
  private CommRanklistRelativePowerResponseProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommRanklistRelativePowerResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CommRanklistRelativePowerResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 result = 10;</code>
     */
    int getResult();

    /**
     * <code>.CommRanklistRelativePowerRequest request = 11;</code>
     */
    boolean hasRequest();
    /**
     * <code>.CommRanklistRelativePowerRequest request = 11;</code>
     */
    com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest getRequest();
    /**
     * <code>.CommRanklistRelativePowerRequest request = 11;</code>
     */
    com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequestOrBuilder getRequestOrBuilder();

    /**
     * <code>repeated .Ranklist ranks = 12;</code>
     */
    java.util.List<com.gejian.pixel.proto.RanklistProtobuf.Ranklist> 
        getRanksList();
    /**
     * <code>repeated .Ranklist ranks = 12;</code>
     */
    com.gejian.pixel.proto.RanklistProtobuf.Ranklist getRanks(int index);
    /**
     * <code>repeated .Ranklist ranks = 12;</code>
     */
    int getRanksCount();
    /**
     * <code>repeated .Ranklist ranks = 12;</code>
     */
    java.util.List<? extends com.gejian.pixel.proto.RanklistProtobuf.RanklistOrBuilder> 
        getRanksOrBuilderList();
    /**
     * <code>repeated .Ranklist ranks = 12;</code>
     */
    com.gejian.pixel.proto.RanklistProtobuf.RanklistOrBuilder getRanksOrBuilder(
        int index);

    /**
     * <code>repeated .PlayerItem items = 13;</code>
     */
    java.util.List<com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem> 
        getItemsList();
    /**
     * <code>repeated .PlayerItem items = 13;</code>
     */
    com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem getItems(int index);
    /**
     * <code>repeated .PlayerItem items = 13;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .PlayerItem items = 13;</code>
     */
    java.util.List<? extends com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .PlayerItem items = 13;</code>
     */
    com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItemOrBuilder getItemsOrBuilder(
        int index);

    /**
     * <code>repeated .PlayerItem archives = 14;</code>
     */
    java.util.List<com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem> 
        getArchivesList();
    /**
     * <code>repeated .PlayerItem archives = 14;</code>
     */
    com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem getArchives(int index);
    /**
     * <code>repeated .PlayerItem archives = 14;</code>
     */
    int getArchivesCount();
    /**
     * <code>repeated .PlayerItem archives = 14;</code>
     */
    java.util.List<? extends com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItemOrBuilder> 
        getArchivesOrBuilderList();
    /**
     * <code>repeated .PlayerItem archives = 14;</code>
     */
    com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItemOrBuilder getArchivesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code CommRanklistRelativePowerResponse}
   */
  public  static final class CommRanklistRelativePowerResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CommRanklistRelativePowerResponse)
      CommRanklistRelativePowerResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommRanklistRelativePowerResponse.newBuilder() to construct.
    private CommRanklistRelativePowerResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommRanklistRelativePowerResponse() {
      result_ = 0;
      ranks_ = java.util.Collections.emptyList();
      items_ = java.util.Collections.emptyList();
      archives_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommRanklistRelativePowerResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 80: {

              result_ = input.readUInt32();
              break;
            }
            case 90: {
              com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 98: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                ranks_ = new java.util.ArrayList<com.gejian.pixel.proto.RanklistProtobuf.Ranklist>();
                mutable_bitField0_ |= 0x00000004;
              }
              ranks_.add(
                  input.readMessage(com.gejian.pixel.proto.RanklistProtobuf.Ranklist.parser(), extensionRegistry));
              break;
            }
            case 106: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                items_ = new java.util.ArrayList<com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem>();
                mutable_bitField0_ |= 0x00000008;
              }
              items_.add(
                  input.readMessage(com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.parser(), extensionRegistry));
              break;
            }
            case 114: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                archives_ = new java.util.ArrayList<com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem>();
                mutable_bitField0_ |= 0x00000010;
              }
              archives_.add(
                  input.readMessage(com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          ranks_ = java.util.Collections.unmodifiableList(ranks_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          archives_ = java.util.Collections.unmodifiableList(archives_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.internal_static_CommRanklistRelativePowerResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.internal_static_CommRanklistRelativePowerResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse.class, com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse.Builder.class);
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 10;
    private int result_;
    /**
     * <code>uint32 result = 10;</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int REQUEST_FIELD_NUMBER = 11;
    private com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest request_;
    /**
     * <code>.CommRanklistRelativePowerRequest request = 11;</code>
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>.CommRanklistRelativePowerRequest request = 11;</code>
     */
    public com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest getRequest() {
      return request_ == null ? com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest.getDefaultInstance() : request_;
    }
    /**
     * <code>.CommRanklistRelativePowerRequest request = 11;</code>
     */
    public com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int RANKS_FIELD_NUMBER = 12;
    private java.util.List<com.gejian.pixel.proto.RanklistProtobuf.Ranklist> ranks_;
    /**
     * <code>repeated .Ranklist ranks = 12;</code>
     */
    public java.util.List<com.gejian.pixel.proto.RanklistProtobuf.Ranklist> getRanksList() {
      return ranks_;
    }
    /**
     * <code>repeated .Ranklist ranks = 12;</code>
     */
    public java.util.List<? extends com.gejian.pixel.proto.RanklistProtobuf.RanklistOrBuilder> 
        getRanksOrBuilderList() {
      return ranks_;
    }
    /**
     * <code>repeated .Ranklist ranks = 12;</code>
     */
    public int getRanksCount() {
      return ranks_.size();
    }
    /**
     * <code>repeated .Ranklist ranks = 12;</code>
     */
    public com.gejian.pixel.proto.RanklistProtobuf.Ranklist getRanks(int index) {
      return ranks_.get(index);
    }
    /**
     * <code>repeated .Ranklist ranks = 12;</code>
     */
    public com.gejian.pixel.proto.RanklistProtobuf.RanklistOrBuilder getRanksOrBuilder(
        int index) {
      return ranks_.get(index);
    }

    public static final int ITEMS_FIELD_NUMBER = 13;
    private java.util.List<com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem> items_;
    /**
     * <code>repeated .PlayerItem items = 13;</code>
     */
    public java.util.List<com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .PlayerItem items = 13;</code>
     */
    public java.util.List<? extends com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .PlayerItem items = 13;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .PlayerItem items = 13;</code>
     */
    public com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .PlayerItem items = 13;</code>
     */
    public com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    public static final int ARCHIVES_FIELD_NUMBER = 14;
    private java.util.List<com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem> archives_;
    /**
     * <code>repeated .PlayerItem archives = 14;</code>
     */
    public java.util.List<com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem> getArchivesList() {
      return archives_;
    }
    /**
     * <code>repeated .PlayerItem archives = 14;</code>
     */
    public java.util.List<? extends com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItemOrBuilder> 
        getArchivesOrBuilderList() {
      return archives_;
    }
    /**
     * <code>repeated .PlayerItem archives = 14;</code>
     */
    public int getArchivesCount() {
      return archives_.size();
    }
    /**
     * <code>repeated .PlayerItem archives = 14;</code>
     */
    public com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem getArchives(int index) {
      return archives_.get(index);
    }
    /**
     * <code>repeated .PlayerItem archives = 14;</code>
     */
    public com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItemOrBuilder getArchivesOrBuilder(
        int index) {
      return archives_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != 0) {
        output.writeUInt32(10, result_);
      }
      if (request_ != null) {
        output.writeMessage(11, getRequest());
      }
      for (int i = 0; i < ranks_.size(); i++) {
        output.writeMessage(12, ranks_.get(i));
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(13, items_.get(i));
      }
      for (int i = 0; i < archives_.size(); i++) {
        output.writeMessage(14, archives_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, result_);
      }
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, getRequest());
      }
      for (int i = 0; i < ranks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, ranks_.get(i));
      }
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, items_.get(i));
      }
      for (int i = 0; i < archives_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(14, archives_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse)) {
        return super.equals(obj);
      }
      com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse other = (com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse) obj;

      boolean result = true;
      result = result && (getResult()
          == other.getResult());
      result = result && (hasRequest() == other.hasRequest());
      if (hasRequest()) {
        result = result && getRequest()
            .equals(other.getRequest());
      }
      result = result && getRanksList()
          .equals(other.getRanksList());
      result = result && getItemsList()
          .equals(other.getItemsList());
      result = result && getArchivesList()
          .equals(other.getArchivesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      if (getRanksCount() > 0) {
        hash = (37 * hash) + RANKS_FIELD_NUMBER;
        hash = (53 * hash) + getRanksList().hashCode();
      }
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      if (getArchivesCount() > 0) {
        hash = (37 * hash) + ARCHIVES_FIELD_NUMBER;
        hash = (53 * hash) + getArchivesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommRanklistRelativePowerResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CommRanklistRelativePowerResponse)
        com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.internal_static_CommRanklistRelativePowerResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.internal_static_CommRanklistRelativePowerResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse.class, com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse.Builder.class);
      }

      // Construct using com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRanksFieldBuilder();
          getItemsFieldBuilder();
          getArchivesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = 0;

        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        if (ranksBuilder_ == null) {
          ranks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ranksBuilder_.clear();
        }
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          itemsBuilder_.clear();
        }
        if (archivesBuilder_ == null) {
          archives_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          archivesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.internal_static_CommRanklistRelativePowerResponse_descriptor;
      }

      @java.lang.Override
      public com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse getDefaultInstanceForType() {
        return com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse build() {
        com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse buildPartial() {
        com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse result = new com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.result_ = result_;
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (ranksBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            ranks_ = java.util.Collections.unmodifiableList(ranks_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.ranks_ = ranks_;
        } else {
          result.ranks_ = ranksBuilder_.build();
        }
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        if (archivesBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            archives_ = java.util.Collections.unmodifiableList(archives_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.archives_ = archives_;
        } else {
          result.archives_ = archivesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse) {
          return mergeFrom((com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse other) {
        if (other == com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse.getDefaultInstance()) return this;
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (ranksBuilder_ == null) {
          if (!other.ranks_.isEmpty()) {
            if (ranks_.isEmpty()) {
              ranks_ = other.ranks_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureRanksIsMutable();
              ranks_.addAll(other.ranks_);
            }
            onChanged();
          }
        } else {
          if (!other.ranks_.isEmpty()) {
            if (ranksBuilder_.isEmpty()) {
              ranksBuilder_.dispose();
              ranksBuilder_ = null;
              ranks_ = other.ranks_;
              bitField0_ = (bitField0_ & ~0x00000004);
              ranksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRanksFieldBuilder() : null;
            } else {
              ranksBuilder_.addAllMessages(other.ranks_);
            }
          }
        }
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000008);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        if (archivesBuilder_ == null) {
          if (!other.archives_.isEmpty()) {
            if (archives_.isEmpty()) {
              archives_ = other.archives_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureArchivesIsMutable();
              archives_.addAll(other.archives_);
            }
            onChanged();
          }
        } else {
          if (!other.archives_.isEmpty()) {
            if (archivesBuilder_.isEmpty()) {
              archivesBuilder_.dispose();
              archivesBuilder_ = null;
              archives_ = other.archives_;
              bitField0_ = (bitField0_ & ~0x00000010);
              archivesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getArchivesFieldBuilder() : null;
            } else {
              archivesBuilder_.addAllMessages(other.archives_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int result_ ;
      /**
       * <code>uint32 result = 10;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>uint32 result = 10;</code>
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 result = 10;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest request_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest, com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest.Builder, com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequestOrBuilder> requestBuilder_;
      /**
       * <code>.CommRanklistRelativePowerRequest request = 11;</code>
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>.CommRanklistRelativePowerRequest request = 11;</code>
       */
      public com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>.CommRanklistRelativePowerRequest request = 11;</code>
       */
      public Builder setRequest(com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CommRanklistRelativePowerRequest request = 11;</code>
       */
      public Builder setRequest(
          com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CommRanklistRelativePowerRequest request = 11;</code>
       */
      public Builder mergeRequest(com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CommRanklistRelativePowerRequest request = 11;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CommRanklistRelativePowerRequest request = 11;</code>
       */
      public com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.CommRanklistRelativePowerRequest request = 11;</code>
       */
      public com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>.CommRanklistRelativePowerRequest request = 11;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest, com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest.Builder, com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest, com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequest.Builder, com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.CommRanklistRelativePowerRequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private java.util.List<com.gejian.pixel.proto.RanklistProtobuf.Ranklist> ranks_ =
        java.util.Collections.emptyList();
      private void ensureRanksIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          ranks_ = new java.util.ArrayList<com.gejian.pixel.proto.RanklistProtobuf.Ranklist>(ranks_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.gejian.pixel.proto.RanklistProtobuf.Ranklist, com.gejian.pixel.proto.RanklistProtobuf.Ranklist.Builder, com.gejian.pixel.proto.RanklistProtobuf.RanklistOrBuilder> ranksBuilder_;

      /**
       * <code>repeated .Ranklist ranks = 12;</code>
       */
      public java.util.List<com.gejian.pixel.proto.RanklistProtobuf.Ranklist> getRanksList() {
        if (ranksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ranks_);
        } else {
          return ranksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Ranklist ranks = 12;</code>
       */
      public int getRanksCount() {
        if (ranksBuilder_ == null) {
          return ranks_.size();
        } else {
          return ranksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Ranklist ranks = 12;</code>
       */
      public com.gejian.pixel.proto.RanklistProtobuf.Ranklist getRanks(int index) {
        if (ranksBuilder_ == null) {
          return ranks_.get(index);
        } else {
          return ranksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Ranklist ranks = 12;</code>
       */
      public Builder setRanks(
          int index, com.gejian.pixel.proto.RanklistProtobuf.Ranklist value) {
        if (ranksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRanksIsMutable();
          ranks_.set(index, value);
          onChanged();
        } else {
          ranksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Ranklist ranks = 12;</code>
       */
      public Builder setRanks(
          int index, com.gejian.pixel.proto.RanklistProtobuf.Ranklist.Builder builderForValue) {
        if (ranksBuilder_ == null) {
          ensureRanksIsMutable();
          ranks_.set(index, builderForValue.build());
          onChanged();
        } else {
          ranksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Ranklist ranks = 12;</code>
       */
      public Builder addRanks(com.gejian.pixel.proto.RanklistProtobuf.Ranklist value) {
        if (ranksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRanksIsMutable();
          ranks_.add(value);
          onChanged();
        } else {
          ranksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Ranklist ranks = 12;</code>
       */
      public Builder addRanks(
          int index, com.gejian.pixel.proto.RanklistProtobuf.Ranklist value) {
        if (ranksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRanksIsMutable();
          ranks_.add(index, value);
          onChanged();
        } else {
          ranksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Ranklist ranks = 12;</code>
       */
      public Builder addRanks(
          com.gejian.pixel.proto.RanklistProtobuf.Ranklist.Builder builderForValue) {
        if (ranksBuilder_ == null) {
          ensureRanksIsMutable();
          ranks_.add(builderForValue.build());
          onChanged();
        } else {
          ranksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Ranklist ranks = 12;</code>
       */
      public Builder addRanks(
          int index, com.gejian.pixel.proto.RanklistProtobuf.Ranklist.Builder builderForValue) {
        if (ranksBuilder_ == null) {
          ensureRanksIsMutable();
          ranks_.add(index, builderForValue.build());
          onChanged();
        } else {
          ranksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Ranklist ranks = 12;</code>
       */
      public Builder addAllRanks(
          java.lang.Iterable<? extends com.gejian.pixel.proto.RanklistProtobuf.Ranklist> values) {
        if (ranksBuilder_ == null) {
          ensureRanksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ranks_);
          onChanged();
        } else {
          ranksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Ranklist ranks = 12;</code>
       */
      public Builder clearRanks() {
        if (ranksBuilder_ == null) {
          ranks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          ranksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Ranklist ranks = 12;</code>
       */
      public Builder removeRanks(int index) {
        if (ranksBuilder_ == null) {
          ensureRanksIsMutable();
          ranks_.remove(index);
          onChanged();
        } else {
          ranksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Ranklist ranks = 12;</code>
       */
      public com.gejian.pixel.proto.RanklistProtobuf.Ranklist.Builder getRanksBuilder(
          int index) {
        return getRanksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Ranklist ranks = 12;</code>
       */
      public com.gejian.pixel.proto.RanklistProtobuf.RanklistOrBuilder getRanksOrBuilder(
          int index) {
        if (ranksBuilder_ == null) {
          return ranks_.get(index);  } else {
          return ranksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Ranklist ranks = 12;</code>
       */
      public java.util.List<? extends com.gejian.pixel.proto.RanklistProtobuf.RanklistOrBuilder> 
           getRanksOrBuilderList() {
        if (ranksBuilder_ != null) {
          return ranksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ranks_);
        }
      }
      /**
       * <code>repeated .Ranklist ranks = 12;</code>
       */
      public com.gejian.pixel.proto.RanklistProtobuf.Ranklist.Builder addRanksBuilder() {
        return getRanksFieldBuilder().addBuilder(
            com.gejian.pixel.proto.RanklistProtobuf.Ranklist.getDefaultInstance());
      }
      /**
       * <code>repeated .Ranklist ranks = 12;</code>
       */
      public com.gejian.pixel.proto.RanklistProtobuf.Ranklist.Builder addRanksBuilder(
          int index) {
        return getRanksFieldBuilder().addBuilder(
            index, com.gejian.pixel.proto.RanklistProtobuf.Ranklist.getDefaultInstance());
      }
      /**
       * <code>repeated .Ranklist ranks = 12;</code>
       */
      public java.util.List<com.gejian.pixel.proto.RanklistProtobuf.Ranklist.Builder> 
           getRanksBuilderList() {
        return getRanksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.gejian.pixel.proto.RanklistProtobuf.Ranklist, com.gejian.pixel.proto.RanklistProtobuf.Ranklist.Builder, com.gejian.pixel.proto.RanklistProtobuf.RanklistOrBuilder> 
          getRanksFieldBuilder() {
        if (ranksBuilder_ == null) {
          ranksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.gejian.pixel.proto.RanklistProtobuf.Ranklist, com.gejian.pixel.proto.RanklistProtobuf.Ranklist.Builder, com.gejian.pixel.proto.RanklistProtobuf.RanklistOrBuilder>(
                  ranks_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          ranks_ = null;
        }
        return ranksBuilder_;
      }

      private java.util.List<com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          items_ = new java.util.ArrayList<com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem>(items_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .PlayerItem items = 13;</code>
       */
      public java.util.List<com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PlayerItem items = 13;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PlayerItem items = 13;</code>
       */
      public com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PlayerItem items = 13;</code>
       */
      public Builder setItems(
          int index, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PlayerItem items = 13;</code>
       */
      public Builder setItems(
          int index, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PlayerItem items = 13;</code>
       */
      public Builder addItems(com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PlayerItem items = 13;</code>
       */
      public Builder addItems(
          int index, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PlayerItem items = 13;</code>
       */
      public Builder addItems(
          com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PlayerItem items = 13;</code>
       */
      public Builder addItems(
          int index, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PlayerItem items = 13;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PlayerItem items = 13;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PlayerItem items = 13;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PlayerItem items = 13;</code>
       */
      public com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PlayerItem items = 13;</code>
       */
      public com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PlayerItem items = 13;</code>
       */
      public java.util.List<? extends com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .PlayerItem items = 13;</code>
       */
      public com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.getDefaultInstance());
      }
      /**
       * <code>repeated .PlayerItem items = 13;</code>
       */
      public com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.getDefaultInstance());
      }
      /**
       * <code>repeated .PlayerItem items = 13;</code>
       */
      public java.util.List<com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      private java.util.List<com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem> archives_ =
        java.util.Collections.emptyList();
      private void ensureArchivesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          archives_ = new java.util.ArrayList<com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem>(archives_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItemOrBuilder> archivesBuilder_;

      /**
       * <code>repeated .PlayerItem archives = 14;</code>
       */
      public java.util.List<com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem> getArchivesList() {
        if (archivesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(archives_);
        } else {
          return archivesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PlayerItem archives = 14;</code>
       */
      public int getArchivesCount() {
        if (archivesBuilder_ == null) {
          return archives_.size();
        } else {
          return archivesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PlayerItem archives = 14;</code>
       */
      public com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem getArchives(int index) {
        if (archivesBuilder_ == null) {
          return archives_.get(index);
        } else {
          return archivesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PlayerItem archives = 14;</code>
       */
      public Builder setArchives(
          int index, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem value) {
        if (archivesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArchivesIsMutable();
          archives_.set(index, value);
          onChanged();
        } else {
          archivesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PlayerItem archives = 14;</code>
       */
      public Builder setArchives(
          int index, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder builderForValue) {
        if (archivesBuilder_ == null) {
          ensureArchivesIsMutable();
          archives_.set(index, builderForValue.build());
          onChanged();
        } else {
          archivesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PlayerItem archives = 14;</code>
       */
      public Builder addArchives(com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem value) {
        if (archivesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArchivesIsMutable();
          archives_.add(value);
          onChanged();
        } else {
          archivesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PlayerItem archives = 14;</code>
       */
      public Builder addArchives(
          int index, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem value) {
        if (archivesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArchivesIsMutable();
          archives_.add(index, value);
          onChanged();
        } else {
          archivesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PlayerItem archives = 14;</code>
       */
      public Builder addArchives(
          com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder builderForValue) {
        if (archivesBuilder_ == null) {
          ensureArchivesIsMutable();
          archives_.add(builderForValue.build());
          onChanged();
        } else {
          archivesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PlayerItem archives = 14;</code>
       */
      public Builder addArchives(
          int index, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder builderForValue) {
        if (archivesBuilder_ == null) {
          ensureArchivesIsMutable();
          archives_.add(index, builderForValue.build());
          onChanged();
        } else {
          archivesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PlayerItem archives = 14;</code>
       */
      public Builder addAllArchives(
          java.lang.Iterable<? extends com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem> values) {
        if (archivesBuilder_ == null) {
          ensureArchivesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, archives_);
          onChanged();
        } else {
          archivesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PlayerItem archives = 14;</code>
       */
      public Builder clearArchives() {
        if (archivesBuilder_ == null) {
          archives_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          archivesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PlayerItem archives = 14;</code>
       */
      public Builder removeArchives(int index) {
        if (archivesBuilder_ == null) {
          ensureArchivesIsMutable();
          archives_.remove(index);
          onChanged();
        } else {
          archivesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PlayerItem archives = 14;</code>
       */
      public com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder getArchivesBuilder(
          int index) {
        return getArchivesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PlayerItem archives = 14;</code>
       */
      public com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItemOrBuilder getArchivesOrBuilder(
          int index) {
        if (archivesBuilder_ == null) {
          return archives_.get(index);  } else {
          return archivesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PlayerItem archives = 14;</code>
       */
      public java.util.List<? extends com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItemOrBuilder> 
           getArchivesOrBuilderList() {
        if (archivesBuilder_ != null) {
          return archivesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(archives_);
        }
      }
      /**
       * <code>repeated .PlayerItem archives = 14;</code>
       */
      public com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder addArchivesBuilder() {
        return getArchivesFieldBuilder().addBuilder(
            com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.getDefaultInstance());
      }
      /**
       * <code>repeated .PlayerItem archives = 14;</code>
       */
      public com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder addArchivesBuilder(
          int index) {
        return getArchivesFieldBuilder().addBuilder(
            index, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.getDefaultInstance());
      }
      /**
       * <code>repeated .PlayerItem archives = 14;</code>
       */
      public java.util.List<com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder> 
           getArchivesBuilderList() {
        return getArchivesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItemOrBuilder> 
          getArchivesFieldBuilder() {
        if (archivesBuilder_ == null) {
          archivesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItem.Builder, com.gejian.pixel.proto.PlayerItemProtobuf.PlayerItemOrBuilder>(
                  archives_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          archives_ = null;
        }
        return archivesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CommRanklistRelativePowerResponse)
    }

    // @@protoc_insertion_point(class_scope:CommRanklistRelativePowerResponse)
    private static final com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse();
    }

    public static com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommRanklistRelativePowerResponse>
        PARSER = new com.google.protobuf.AbstractParser<CommRanklistRelativePowerResponse>() {
      @java.lang.Override
      public CommRanklistRelativePowerResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommRanklistRelativePowerResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommRanklistRelativePowerResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommRanklistRelativePowerResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gejian.pixel.proto.CommRanklistRelativePowerResponseProtobuf.CommRanklistRelativePowerResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommRanklistRelativePowerResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommRanklistRelativePowerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'CommRanklistRelativePowerResponse.prot" +
      "o\032&CommRanklistRelativePowerRequest.prot" +
      "o\032\020PlayerItem.proto\032\016Ranklist.proto\"\274\001\n!" +
      "CommRanklistRelativePowerResponse\022\016\n\006res" +
      "ult\030\n \001(\r\0222\n\007request\030\013 \001(\0132!.CommRanklis" +
      "tRelativePowerRequest\022\030\n\005ranks\030\014 \003(\0132\t.R" +
      "anklist\022\032\n\005items\030\r \003(\0132\013.PlayerItem\022\035\n\010a" +
      "rchives\030\016 \003(\0132\013.PlayerItemBC\n\026com.gejian" +
      ".pixel.protoB)CommRanklistRelativePowerR" +
      "esponseProtobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.getDescriptor(),
          com.gejian.pixel.proto.PlayerItemProtobuf.getDescriptor(),
          com.gejian.pixel.proto.RanklistProtobuf.getDescriptor(),
        }, assigner);
    internal_static_CommRanklistRelativePowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CommRanklistRelativePowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommRanklistRelativePowerResponse_descriptor,
        new java.lang.String[] { "Result", "Request", "Ranks", "Items", "Archives", });
    com.gejian.pixel.proto.CommRanklistRelativePowerRequestProtobuf.getDescriptor();
    com.gejian.pixel.proto.PlayerItemProtobuf.getDescriptor();
    com.gejian.pixel.proto.RanklistProtobuf.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
