// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConstVipTableItemEx.proto

package com.gejian.pixel.proto;

public final class ConstVipTableItemExProtobuf {
  private ConstVipTableItemExProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConstVipTableItemExOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConstVipTableItemEx)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>uint32 level = 2;</code>
     */
    int getLevel();

    /**
     * <code>uint32 charge = 3;</code>
     */
    int getCharge();

    /**
     * <code>string itemid = 4;</code>
     */
    java.lang.String getItemid();
    /**
     * <code>string itemid = 4;</code>
     */
    com.google.protobuf.ByteString
        getItemidBytes();

    /**
     * <code>string award = 5;</code>
     */
    java.lang.String getAward();
    /**
     * <code>string award = 5;</code>
     */
    com.google.protobuf.ByteString
        getAwardBytes();

    /**
     * <code>uint32 chanllege = 6;</code>
     */
    int getChanllege();

    /**
     * <code>uint32 backpack_max = 7;</code>
     */
    int getBackpackMax();

    /**
     * <code>uint32 freerefresh_times_stone = 8;</code>
     */
    int getFreerefreshTimesStone();

    /**
     * <code>uint32 freerefresh_times_honor = 9;</code>
     */
    int getFreerefreshTimesHonor();

    /**
     * <code>uint32 freerefresh_times_gold = 10;</code>
     */
    int getFreerefreshTimesGold();

    /**
     * <code>uint32 timeval_offline_kill_monster_rate = 11;</code>
     */
    int getTimevalOfflineKillMonsterRate();

    /**
     * <code>uint32 skip_timeval = 12;</code>
     */
    int getSkipTimeval();

    /**
     * <code>string des = 13;</code>
     */
    java.lang.String getDes();
    /**
     * <code>string des = 13;</code>
     */
    com.google.protobuf.ByteString
        getDesBytes();

    /**
     * <code>uint32 tianti = 14;</code>
     */
    int getTianti();

    /**
     * <code>uint32 tianti_reset = 15;</code>
     */
    int getTiantiReset();
  }
  /**
   * Protobuf type {@code ConstVipTableItemEx}
   */
  public  static final class ConstVipTableItemEx extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConstVipTableItemEx)
      ConstVipTableItemExOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConstVipTableItemEx.newBuilder() to construct.
    private ConstVipTableItemEx(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConstVipTableItemEx() {
      id_ = 0;
      level_ = 0;
      charge_ = 0;
      itemid_ = "";
      award_ = "";
      chanllege_ = 0;
      backpackMax_ = 0;
      freerefreshTimesStone_ = 0;
      freerefreshTimesHonor_ = 0;
      freerefreshTimesGold_ = 0;
      timevalOfflineKillMonsterRate_ = 0;
      skipTimeval_ = 0;
      des_ = "";
      tianti_ = 0;
      tiantiReset_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConstVipTableItemEx(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 16: {

              level_ = input.readUInt32();
              break;
            }
            case 24: {

              charge_ = input.readUInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              itemid_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              award_ = s;
              break;
            }
            case 48: {

              chanllege_ = input.readUInt32();
              break;
            }
            case 56: {

              backpackMax_ = input.readUInt32();
              break;
            }
            case 64: {

              freerefreshTimesStone_ = input.readUInt32();
              break;
            }
            case 72: {

              freerefreshTimesHonor_ = input.readUInt32();
              break;
            }
            case 80: {

              freerefreshTimesGold_ = input.readUInt32();
              break;
            }
            case 88: {

              timevalOfflineKillMonsterRate_ = input.readUInt32();
              break;
            }
            case 96: {

              skipTimeval_ = input.readUInt32();
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              des_ = s;
              break;
            }
            case 112: {

              tianti_ = input.readUInt32();
              break;
            }
            case 120: {

              tiantiReset_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gejian.pixel.proto.ConstVipTableItemExProtobuf.internal_static_ConstVipTableItemEx_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gejian.pixel.proto.ConstVipTableItemExProtobuf.internal_static_ConstVipTableItemEx_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx.class, com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int LEVEL_FIELD_NUMBER = 2;
    private int level_;
    /**
     * <code>uint32 level = 2;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int CHARGE_FIELD_NUMBER = 3;
    private int charge_;
    /**
     * <code>uint32 charge = 3;</code>
     */
    public int getCharge() {
      return charge_;
    }

    public static final int ITEMID_FIELD_NUMBER = 4;
    private volatile java.lang.Object itemid_;
    /**
     * <code>string itemid = 4;</code>
     */
    public java.lang.String getItemid() {
      java.lang.Object ref = itemid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        itemid_ = s;
        return s;
      }
    }
    /**
     * <code>string itemid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getItemidBytes() {
      java.lang.Object ref = itemid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AWARD_FIELD_NUMBER = 5;
    private volatile java.lang.Object award_;
    /**
     * <code>string award = 5;</code>
     */
    public java.lang.String getAward() {
      java.lang.Object ref = award_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        award_ = s;
        return s;
      }
    }
    /**
     * <code>string award = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAwardBytes() {
      java.lang.Object ref = award_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        award_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANLLEGE_FIELD_NUMBER = 6;
    private int chanllege_;
    /**
     * <code>uint32 chanllege = 6;</code>
     */
    public int getChanllege() {
      return chanllege_;
    }

    public static final int BACKPACK_MAX_FIELD_NUMBER = 7;
    private int backpackMax_;
    /**
     * <code>uint32 backpack_max = 7;</code>
     */
    public int getBackpackMax() {
      return backpackMax_;
    }

    public static final int FREEREFRESH_TIMES_STONE_FIELD_NUMBER = 8;
    private int freerefreshTimesStone_;
    /**
     * <code>uint32 freerefresh_times_stone = 8;</code>
     */
    public int getFreerefreshTimesStone() {
      return freerefreshTimesStone_;
    }

    public static final int FREEREFRESH_TIMES_HONOR_FIELD_NUMBER = 9;
    private int freerefreshTimesHonor_;
    /**
     * <code>uint32 freerefresh_times_honor = 9;</code>
     */
    public int getFreerefreshTimesHonor() {
      return freerefreshTimesHonor_;
    }

    public static final int FREEREFRESH_TIMES_GOLD_FIELD_NUMBER = 10;
    private int freerefreshTimesGold_;
    /**
     * <code>uint32 freerefresh_times_gold = 10;</code>
     */
    public int getFreerefreshTimesGold() {
      return freerefreshTimesGold_;
    }

    public static final int TIMEVAL_OFFLINE_KILL_MONSTER_RATE_FIELD_NUMBER = 11;
    private int timevalOfflineKillMonsterRate_;
    /**
     * <code>uint32 timeval_offline_kill_monster_rate = 11;</code>
     */
    public int getTimevalOfflineKillMonsterRate() {
      return timevalOfflineKillMonsterRate_;
    }

    public static final int SKIP_TIMEVAL_FIELD_NUMBER = 12;
    private int skipTimeval_;
    /**
     * <code>uint32 skip_timeval = 12;</code>
     */
    public int getSkipTimeval() {
      return skipTimeval_;
    }

    public static final int DES_FIELD_NUMBER = 13;
    private volatile java.lang.Object des_;
    /**
     * <code>string des = 13;</code>
     */
    public java.lang.String getDes() {
      java.lang.Object ref = des_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        des_ = s;
        return s;
      }
    }
    /**
     * <code>string des = 13;</code>
     */
    public com.google.protobuf.ByteString
        getDesBytes() {
      java.lang.Object ref = des_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        des_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIANTI_FIELD_NUMBER = 14;
    private int tianti_;
    /**
     * <code>uint32 tianti = 14;</code>
     */
    public int getTianti() {
      return tianti_;
    }

    public static final int TIANTI_RESET_FIELD_NUMBER = 15;
    private int tiantiReset_;
    /**
     * <code>uint32 tianti_reset = 15;</code>
     */
    public int getTiantiReset() {
      return tiantiReset_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (level_ != 0) {
        output.writeUInt32(2, level_);
      }
      if (charge_ != 0) {
        output.writeUInt32(3, charge_);
      }
      if (!getItemidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, itemid_);
      }
      if (!getAwardBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, award_);
      }
      if (chanllege_ != 0) {
        output.writeUInt32(6, chanllege_);
      }
      if (backpackMax_ != 0) {
        output.writeUInt32(7, backpackMax_);
      }
      if (freerefreshTimesStone_ != 0) {
        output.writeUInt32(8, freerefreshTimesStone_);
      }
      if (freerefreshTimesHonor_ != 0) {
        output.writeUInt32(9, freerefreshTimesHonor_);
      }
      if (freerefreshTimesGold_ != 0) {
        output.writeUInt32(10, freerefreshTimesGold_);
      }
      if (timevalOfflineKillMonsterRate_ != 0) {
        output.writeUInt32(11, timevalOfflineKillMonsterRate_);
      }
      if (skipTimeval_ != 0) {
        output.writeUInt32(12, skipTimeval_);
      }
      if (!getDesBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, des_);
      }
      if (tianti_ != 0) {
        output.writeUInt32(14, tianti_);
      }
      if (tiantiReset_ != 0) {
        output.writeUInt32(15, tiantiReset_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, level_);
      }
      if (charge_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, charge_);
      }
      if (!getItemidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, itemid_);
      }
      if (!getAwardBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, award_);
      }
      if (chanllege_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, chanllege_);
      }
      if (backpackMax_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, backpackMax_);
      }
      if (freerefreshTimesStone_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, freerefreshTimesStone_);
      }
      if (freerefreshTimesHonor_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, freerefreshTimesHonor_);
      }
      if (freerefreshTimesGold_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, freerefreshTimesGold_);
      }
      if (timevalOfflineKillMonsterRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(11, timevalOfflineKillMonsterRate_);
      }
      if (skipTimeval_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(12, skipTimeval_);
      }
      if (!getDesBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, des_);
      }
      if (tianti_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(14, tianti_);
      }
      if (tiantiReset_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(15, tiantiReset_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx)) {
        return super.equals(obj);
      }
      com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx other = (com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getLevel()
          == other.getLevel());
      result = result && (getCharge()
          == other.getCharge());
      result = result && getItemid()
          .equals(other.getItemid());
      result = result && getAward()
          .equals(other.getAward());
      result = result && (getChanllege()
          == other.getChanllege());
      result = result && (getBackpackMax()
          == other.getBackpackMax());
      result = result && (getFreerefreshTimesStone()
          == other.getFreerefreshTimesStone());
      result = result && (getFreerefreshTimesHonor()
          == other.getFreerefreshTimesHonor());
      result = result && (getFreerefreshTimesGold()
          == other.getFreerefreshTimesGold());
      result = result && (getTimevalOfflineKillMonsterRate()
          == other.getTimevalOfflineKillMonsterRate());
      result = result && (getSkipTimeval()
          == other.getSkipTimeval());
      result = result && getDes()
          .equals(other.getDes());
      result = result && (getTianti()
          == other.getTianti());
      result = result && (getTiantiReset()
          == other.getTiantiReset());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      hash = (37 * hash) + CHARGE_FIELD_NUMBER;
      hash = (53 * hash) + getCharge();
      hash = (37 * hash) + ITEMID_FIELD_NUMBER;
      hash = (53 * hash) + getItemid().hashCode();
      hash = (37 * hash) + AWARD_FIELD_NUMBER;
      hash = (53 * hash) + getAward().hashCode();
      hash = (37 * hash) + CHANLLEGE_FIELD_NUMBER;
      hash = (53 * hash) + getChanllege();
      hash = (37 * hash) + BACKPACK_MAX_FIELD_NUMBER;
      hash = (53 * hash) + getBackpackMax();
      hash = (37 * hash) + FREEREFRESH_TIMES_STONE_FIELD_NUMBER;
      hash = (53 * hash) + getFreerefreshTimesStone();
      hash = (37 * hash) + FREEREFRESH_TIMES_HONOR_FIELD_NUMBER;
      hash = (53 * hash) + getFreerefreshTimesHonor();
      hash = (37 * hash) + FREEREFRESH_TIMES_GOLD_FIELD_NUMBER;
      hash = (53 * hash) + getFreerefreshTimesGold();
      hash = (37 * hash) + TIMEVAL_OFFLINE_KILL_MONSTER_RATE_FIELD_NUMBER;
      hash = (53 * hash) + getTimevalOfflineKillMonsterRate();
      hash = (37 * hash) + SKIP_TIMEVAL_FIELD_NUMBER;
      hash = (53 * hash) + getSkipTimeval();
      hash = (37 * hash) + DES_FIELD_NUMBER;
      hash = (53 * hash) + getDes().hashCode();
      hash = (37 * hash) + TIANTI_FIELD_NUMBER;
      hash = (53 * hash) + getTianti();
      hash = (37 * hash) + TIANTI_RESET_FIELD_NUMBER;
      hash = (53 * hash) + getTiantiReset();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConstVipTableItemEx}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConstVipTableItemEx)
        com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemExOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gejian.pixel.proto.ConstVipTableItemExProtobuf.internal_static_ConstVipTableItemEx_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gejian.pixel.proto.ConstVipTableItemExProtobuf.internal_static_ConstVipTableItemEx_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx.class, com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx.Builder.class);
      }

      // Construct using com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        level_ = 0;

        charge_ = 0;

        itemid_ = "";

        award_ = "";

        chanllege_ = 0;

        backpackMax_ = 0;

        freerefreshTimesStone_ = 0;

        freerefreshTimesHonor_ = 0;

        freerefreshTimesGold_ = 0;

        timevalOfflineKillMonsterRate_ = 0;

        skipTimeval_ = 0;

        des_ = "";

        tianti_ = 0;

        tiantiReset_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gejian.pixel.proto.ConstVipTableItemExProtobuf.internal_static_ConstVipTableItemEx_descriptor;
      }

      @java.lang.Override
      public com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx getDefaultInstanceForType() {
        return com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx.getDefaultInstance();
      }

      @java.lang.Override
      public com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx build() {
        com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx buildPartial() {
        com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx result = new com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx(this);
        result.id_ = id_;
        result.level_ = level_;
        result.charge_ = charge_;
        result.itemid_ = itemid_;
        result.award_ = award_;
        result.chanllege_ = chanllege_;
        result.backpackMax_ = backpackMax_;
        result.freerefreshTimesStone_ = freerefreshTimesStone_;
        result.freerefreshTimesHonor_ = freerefreshTimesHonor_;
        result.freerefreshTimesGold_ = freerefreshTimesGold_;
        result.timevalOfflineKillMonsterRate_ = timevalOfflineKillMonsterRate_;
        result.skipTimeval_ = skipTimeval_;
        result.des_ = des_;
        result.tianti_ = tianti_;
        result.tiantiReset_ = tiantiReset_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx) {
          return mergeFrom((com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx other) {
        if (other == com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        if (other.getCharge() != 0) {
          setCharge(other.getCharge());
        }
        if (!other.getItemid().isEmpty()) {
          itemid_ = other.itemid_;
          onChanged();
        }
        if (!other.getAward().isEmpty()) {
          award_ = other.award_;
          onChanged();
        }
        if (other.getChanllege() != 0) {
          setChanllege(other.getChanllege());
        }
        if (other.getBackpackMax() != 0) {
          setBackpackMax(other.getBackpackMax());
        }
        if (other.getFreerefreshTimesStone() != 0) {
          setFreerefreshTimesStone(other.getFreerefreshTimesStone());
        }
        if (other.getFreerefreshTimesHonor() != 0) {
          setFreerefreshTimesHonor(other.getFreerefreshTimesHonor());
        }
        if (other.getFreerefreshTimesGold() != 0) {
          setFreerefreshTimesGold(other.getFreerefreshTimesGold());
        }
        if (other.getTimevalOfflineKillMonsterRate() != 0) {
          setTimevalOfflineKillMonsterRate(other.getTimevalOfflineKillMonsterRate());
        }
        if (other.getSkipTimeval() != 0) {
          setSkipTimeval(other.getSkipTimeval());
        }
        if (!other.getDes().isEmpty()) {
          des_ = other.des_;
          onChanged();
        }
        if (other.getTianti() != 0) {
          setTianti(other.getTianti());
        }
        if (other.getTiantiReset() != 0) {
          setTiantiReset(other.getTiantiReset());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>uint32 level = 2;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>uint32 level = 2;</code>
       */
      public Builder setLevel(int value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 level = 2;</code>
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }

      private int charge_ ;
      /**
       * <code>uint32 charge = 3;</code>
       */
      public int getCharge() {
        return charge_;
      }
      /**
       * <code>uint32 charge = 3;</code>
       */
      public Builder setCharge(int value) {
        
        charge_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 charge = 3;</code>
       */
      public Builder clearCharge() {
        
        charge_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object itemid_ = "";
      /**
       * <code>string itemid = 4;</code>
       */
      public java.lang.String getItemid() {
        java.lang.Object ref = itemid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          itemid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string itemid = 4;</code>
       */
      public com.google.protobuf.ByteString
          getItemidBytes() {
        java.lang.Object ref = itemid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          itemid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string itemid = 4;</code>
       */
      public Builder setItemid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        itemid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string itemid = 4;</code>
       */
      public Builder clearItemid() {
        
        itemid_ = getDefaultInstance().getItemid();
        onChanged();
        return this;
      }
      /**
       * <code>string itemid = 4;</code>
       */
      public Builder setItemidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        itemid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object award_ = "";
      /**
       * <code>string award = 5;</code>
       */
      public java.lang.String getAward() {
        java.lang.Object ref = award_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          award_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string award = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAwardBytes() {
        java.lang.Object ref = award_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          award_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string award = 5;</code>
       */
      public Builder setAward(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        award_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string award = 5;</code>
       */
      public Builder clearAward() {
        
        award_ = getDefaultInstance().getAward();
        onChanged();
        return this;
      }
      /**
       * <code>string award = 5;</code>
       */
      public Builder setAwardBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        award_ = value;
        onChanged();
        return this;
      }

      private int chanllege_ ;
      /**
       * <code>uint32 chanllege = 6;</code>
       */
      public int getChanllege() {
        return chanllege_;
      }
      /**
       * <code>uint32 chanllege = 6;</code>
       */
      public Builder setChanllege(int value) {
        
        chanllege_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 chanllege = 6;</code>
       */
      public Builder clearChanllege() {
        
        chanllege_ = 0;
        onChanged();
        return this;
      }

      private int backpackMax_ ;
      /**
       * <code>uint32 backpack_max = 7;</code>
       */
      public int getBackpackMax() {
        return backpackMax_;
      }
      /**
       * <code>uint32 backpack_max = 7;</code>
       */
      public Builder setBackpackMax(int value) {
        
        backpackMax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 backpack_max = 7;</code>
       */
      public Builder clearBackpackMax() {
        
        backpackMax_ = 0;
        onChanged();
        return this;
      }

      private int freerefreshTimesStone_ ;
      /**
       * <code>uint32 freerefresh_times_stone = 8;</code>
       */
      public int getFreerefreshTimesStone() {
        return freerefreshTimesStone_;
      }
      /**
       * <code>uint32 freerefresh_times_stone = 8;</code>
       */
      public Builder setFreerefreshTimesStone(int value) {
        
        freerefreshTimesStone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 freerefresh_times_stone = 8;</code>
       */
      public Builder clearFreerefreshTimesStone() {
        
        freerefreshTimesStone_ = 0;
        onChanged();
        return this;
      }

      private int freerefreshTimesHonor_ ;
      /**
       * <code>uint32 freerefresh_times_honor = 9;</code>
       */
      public int getFreerefreshTimesHonor() {
        return freerefreshTimesHonor_;
      }
      /**
       * <code>uint32 freerefresh_times_honor = 9;</code>
       */
      public Builder setFreerefreshTimesHonor(int value) {
        
        freerefreshTimesHonor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 freerefresh_times_honor = 9;</code>
       */
      public Builder clearFreerefreshTimesHonor() {
        
        freerefreshTimesHonor_ = 0;
        onChanged();
        return this;
      }

      private int freerefreshTimesGold_ ;
      /**
       * <code>uint32 freerefresh_times_gold = 10;</code>
       */
      public int getFreerefreshTimesGold() {
        return freerefreshTimesGold_;
      }
      /**
       * <code>uint32 freerefresh_times_gold = 10;</code>
       */
      public Builder setFreerefreshTimesGold(int value) {
        
        freerefreshTimesGold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 freerefresh_times_gold = 10;</code>
       */
      public Builder clearFreerefreshTimesGold() {
        
        freerefreshTimesGold_ = 0;
        onChanged();
        return this;
      }

      private int timevalOfflineKillMonsterRate_ ;
      /**
       * <code>uint32 timeval_offline_kill_monster_rate = 11;</code>
       */
      public int getTimevalOfflineKillMonsterRate() {
        return timevalOfflineKillMonsterRate_;
      }
      /**
       * <code>uint32 timeval_offline_kill_monster_rate = 11;</code>
       */
      public Builder setTimevalOfflineKillMonsterRate(int value) {
        
        timevalOfflineKillMonsterRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 timeval_offline_kill_monster_rate = 11;</code>
       */
      public Builder clearTimevalOfflineKillMonsterRate() {
        
        timevalOfflineKillMonsterRate_ = 0;
        onChanged();
        return this;
      }

      private int skipTimeval_ ;
      /**
       * <code>uint32 skip_timeval = 12;</code>
       */
      public int getSkipTimeval() {
        return skipTimeval_;
      }
      /**
       * <code>uint32 skip_timeval = 12;</code>
       */
      public Builder setSkipTimeval(int value) {
        
        skipTimeval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 skip_timeval = 12;</code>
       */
      public Builder clearSkipTimeval() {
        
        skipTimeval_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object des_ = "";
      /**
       * <code>string des = 13;</code>
       */
      public java.lang.String getDes() {
        java.lang.Object ref = des_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          des_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string des = 13;</code>
       */
      public com.google.protobuf.ByteString
          getDesBytes() {
        java.lang.Object ref = des_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          des_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string des = 13;</code>
       */
      public Builder setDes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        des_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string des = 13;</code>
       */
      public Builder clearDes() {
        
        des_ = getDefaultInstance().getDes();
        onChanged();
        return this;
      }
      /**
       * <code>string des = 13;</code>
       */
      public Builder setDesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        des_ = value;
        onChanged();
        return this;
      }

      private int tianti_ ;
      /**
       * <code>uint32 tianti = 14;</code>
       */
      public int getTianti() {
        return tianti_;
      }
      /**
       * <code>uint32 tianti = 14;</code>
       */
      public Builder setTianti(int value) {
        
        tianti_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 tianti = 14;</code>
       */
      public Builder clearTianti() {
        
        tianti_ = 0;
        onChanged();
        return this;
      }

      private int tiantiReset_ ;
      /**
       * <code>uint32 tianti_reset = 15;</code>
       */
      public int getTiantiReset() {
        return tiantiReset_;
      }
      /**
       * <code>uint32 tianti_reset = 15;</code>
       */
      public Builder setTiantiReset(int value) {
        
        tiantiReset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 tianti_reset = 15;</code>
       */
      public Builder clearTiantiReset() {
        
        tiantiReset_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConstVipTableItemEx)
    }

    // @@protoc_insertion_point(class_scope:ConstVipTableItemEx)
    private static final com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx();
    }

    public static com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConstVipTableItemEx>
        PARSER = new com.google.protobuf.AbstractParser<ConstVipTableItemEx>() {
      @java.lang.Override
      public ConstVipTableItemEx parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConstVipTableItemEx(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConstVipTableItemEx> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConstVipTableItemEx> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gejian.pixel.proto.ConstVipTableItemExProtobuf.ConstVipTableItemEx getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConstVipTableItemEx_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConstVipTableItemEx_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ConstVipTableItemEx.proto\"\336\002\n\023ConstVip" +
      "TableItemEx\022\n\n\002id\030\001 \001(\r\022\r\n\005level\030\002 \001(\r\022\016" +
      "\n\006charge\030\003 \001(\r\022\016\n\006itemid\030\004 \001(\t\022\r\n\005award\030" +
      "\005 \001(\t\022\021\n\tchanllege\030\006 \001(\r\022\024\n\014backpack_max" +
      "\030\007 \001(\r\022\037\n\027freerefresh_times_stone\030\010 \001(\r\022" +
      "\037\n\027freerefresh_times_honor\030\t \001(\r\022\036\n\026free" +
      "refresh_times_gold\030\n \001(\r\022)\n!timeval_offl" +
      "ine_kill_monster_rate\030\013 \001(\r\022\024\n\014skip_time" +
      "val\030\014 \001(\r\022\013\n\003des\030\r \001(\t\022\016\n\006tianti\030\016 \001(\r\022\024" +
      "\n\014tianti_reset\030\017 \001(\rB5\n\026com.gejian.pixel" +
      ".protoB\033ConstVipTableItemExProtobufb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ConstVipTableItemEx_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConstVipTableItemEx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConstVipTableItemEx_descriptor,
        new java.lang.String[] { "Id", "Level", "Charge", "Itemid", "Award", "Chanllege", "BackpackMax", "FreerefreshTimesStone", "FreerefreshTimesHonor", "FreerefreshTimesGold", "TimevalOfflineKillMonsterRate", "SkipTimeval", "Des", "Tianti", "TiantiReset", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
