// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Promotion.proto

package com.gejian.pixel.proto;

public final class PromotionProtobuf {
  private PromotionProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PromotionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Promotion)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **id
     * </pre>
     *
     * <code>uint32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     **标题
     * </pre>
     *
     * <code>string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <pre>
     **标题
     * </pre>
     *
     * <code>string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <pre>
     **关键字
     * </pre>
     *
     * <code>string key = 3;</code>
     */
    java.lang.String getKey();
    /**
     * <pre>
     **关键字
     * </pre>
     *
     * <code>string key = 3;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <pre>
     **类型
     * </pre>
     *
     * <code>uint32 type = 4;</code>
     */
    int getType();

    /**
     * <pre>
     **desc
     * </pre>
     *
     * <code>string desc = 5;</code>
     */
    java.lang.String getDesc();
    /**
     * <pre>
     **desc
     * </pre>
     *
     * <code>string desc = 5;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <pre>
     **比较类型 &lt; &lt;= = &gt;= &gt; 从0开始
     * </pre>
     *
     * <code>uint32 compare_type = 6;</code>
     */
    int getCompareType();

    /**
     * <pre>
     **参数
     * </pre>
     *
     * <code>uint32 parameter = 7;</code>
     */
    int getParameter();

    /**
     * <pre>
     **precondition
     * </pre>
     *
     * <code>uint32 precondition = 8;</code>
     */
    int getPrecondition();

    /**
     * <pre>
     **下一个任务
     * </pre>
     *
     * <code>uint32 next = 9;</code>
     */
    int getNext();

    /**
     * <pre>
     **奖励
     * </pre>
     *
     * <code>string award = 10;</code>
     */
    java.lang.String getAward();
    /**
     * <pre>
     **奖励
     * </pre>
     *
     * <code>string award = 10;</code>
     */
    com.google.protobuf.ByteString
        getAwardBytes();

    /**
     * <pre>
     **进度
     * </pre>
     *
     * <code>string percent = 11;</code>
     */
    java.lang.String getPercent();
    /**
     * <pre>
     **进度
     * </pre>
     *
     * <code>string percent = 11;</code>
     */
    com.google.protobuf.ByteString
        getPercentBytes();
  }
  /**
   * Protobuf type {@code Promotion}
   */
  public  static final class Promotion extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Promotion)
      PromotionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Promotion.newBuilder() to construct.
    private Promotion(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Promotion() {
      id_ = 0;
      title_ = "";
      key_ = "";
      type_ = 0;
      desc_ = "";
      compareType_ = 0;
      parameter_ = 0;
      precondition_ = 0;
      next_ = 0;
      award_ = "";
      percent_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Promotion(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 32: {

              type_ = input.readUInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              desc_ = s;
              break;
            }
            case 48: {

              compareType_ = input.readUInt32();
              break;
            }
            case 56: {

              parameter_ = input.readUInt32();
              break;
            }
            case 64: {

              precondition_ = input.readUInt32();
              break;
            }
            case 72: {

              next_ = input.readUInt32();
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              award_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              percent_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gejian.pixel.proto.PromotionProtobuf.internal_static_Promotion_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gejian.pixel.proto.PromotionProtobuf.internal_static_Promotion_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gejian.pixel.proto.PromotionProtobuf.Promotion.class, com.gejian.pixel.proto.PromotionProtobuf.Promotion.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     **id
     * </pre>
     *
     * <code>uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <pre>
     **标题
     * </pre>
     *
     * <code>string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **标题
     * </pre>
     *
     * <code>string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_FIELD_NUMBER = 3;
    private volatile java.lang.Object key_;
    /**
     * <pre>
     **关键字
     * </pre>
     *
     * <code>string key = 3;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **关键字
     * </pre>
     *
     * <code>string key = 3;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <pre>
     **类型
     * </pre>
     *
     * <code>uint32 type = 4;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int DESC_FIELD_NUMBER = 5;
    private volatile java.lang.Object desc_;
    /**
     * <pre>
     **desc
     * </pre>
     *
     * <code>string desc = 5;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **desc
     * </pre>
     *
     * <code>string desc = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPARE_TYPE_FIELD_NUMBER = 6;
    private int compareType_;
    /**
     * <pre>
     **比较类型 &lt; &lt;= = &gt;= &gt; 从0开始
     * </pre>
     *
     * <code>uint32 compare_type = 6;</code>
     */
    public int getCompareType() {
      return compareType_;
    }

    public static final int PARAMETER_FIELD_NUMBER = 7;
    private int parameter_;
    /**
     * <pre>
     **参数
     * </pre>
     *
     * <code>uint32 parameter = 7;</code>
     */
    public int getParameter() {
      return parameter_;
    }

    public static final int PRECONDITION_FIELD_NUMBER = 8;
    private int precondition_;
    /**
     * <pre>
     **precondition
     * </pre>
     *
     * <code>uint32 precondition = 8;</code>
     */
    public int getPrecondition() {
      return precondition_;
    }

    public static final int NEXT_FIELD_NUMBER = 9;
    private int next_;
    /**
     * <pre>
     **下一个任务
     * </pre>
     *
     * <code>uint32 next = 9;</code>
     */
    public int getNext() {
      return next_;
    }

    public static final int AWARD_FIELD_NUMBER = 10;
    private volatile java.lang.Object award_;
    /**
     * <pre>
     **奖励
     * </pre>
     *
     * <code>string award = 10;</code>
     */
    public java.lang.String getAward() {
      java.lang.Object ref = award_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        award_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **奖励
     * </pre>
     *
     * <code>string award = 10;</code>
     */
    public com.google.protobuf.ByteString
        getAwardBytes() {
      java.lang.Object ref = award_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        award_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERCENT_FIELD_NUMBER = 11;
    private volatile java.lang.Object percent_;
    /**
     * <pre>
     **进度
     * </pre>
     *
     * <code>string percent = 11;</code>
     */
    public java.lang.String getPercent() {
      java.lang.Object ref = percent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        percent_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **进度
     * </pre>
     *
     * <code>string percent = 11;</code>
     */
    public com.google.protobuf.ByteString
        getPercentBytes() {
      java.lang.Object ref = percent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        percent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, key_);
      }
      if (type_ != 0) {
        output.writeUInt32(4, type_);
      }
      if (!getDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, desc_);
      }
      if (compareType_ != 0) {
        output.writeUInt32(6, compareType_);
      }
      if (parameter_ != 0) {
        output.writeUInt32(7, parameter_);
      }
      if (precondition_ != 0) {
        output.writeUInt32(8, precondition_);
      }
      if (next_ != 0) {
        output.writeUInt32(9, next_);
      }
      if (!getAwardBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, award_);
      }
      if (!getPercentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, percent_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, key_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, type_);
      }
      if (!getDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, desc_);
      }
      if (compareType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, compareType_);
      }
      if (parameter_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, parameter_);
      }
      if (precondition_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, precondition_);
      }
      if (next_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, next_);
      }
      if (!getAwardBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, award_);
      }
      if (!getPercentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, percent_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gejian.pixel.proto.PromotionProtobuf.Promotion)) {
        return super.equals(obj);
      }
      com.gejian.pixel.proto.PromotionProtobuf.Promotion other = (com.gejian.pixel.proto.PromotionProtobuf.Promotion) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && getKey()
          .equals(other.getKey());
      result = result && (getType()
          == other.getType());
      result = result && getDesc()
          .equals(other.getDesc());
      result = result && (getCompareType()
          == other.getCompareType());
      result = result && (getParameter()
          == other.getParameter());
      result = result && (getPrecondition()
          == other.getPrecondition());
      result = result && (getNext()
          == other.getNext());
      result = result && getAward()
          .equals(other.getAward());
      result = result && getPercent()
          .equals(other.getPercent());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
      hash = (37 * hash) + COMPARE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCompareType();
      hash = (37 * hash) + PARAMETER_FIELD_NUMBER;
      hash = (53 * hash) + getParameter();
      hash = (37 * hash) + PRECONDITION_FIELD_NUMBER;
      hash = (53 * hash) + getPrecondition();
      hash = (37 * hash) + NEXT_FIELD_NUMBER;
      hash = (53 * hash) + getNext();
      hash = (37 * hash) + AWARD_FIELD_NUMBER;
      hash = (53 * hash) + getAward().hashCode();
      hash = (37 * hash) + PERCENT_FIELD_NUMBER;
      hash = (53 * hash) + getPercent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gejian.pixel.proto.PromotionProtobuf.Promotion parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gejian.pixel.proto.PromotionProtobuf.Promotion parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gejian.pixel.proto.PromotionProtobuf.Promotion parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gejian.pixel.proto.PromotionProtobuf.Promotion parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gejian.pixel.proto.PromotionProtobuf.Promotion parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gejian.pixel.proto.PromotionProtobuf.Promotion parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gejian.pixel.proto.PromotionProtobuf.Promotion parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gejian.pixel.proto.PromotionProtobuf.Promotion parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gejian.pixel.proto.PromotionProtobuf.Promotion parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gejian.pixel.proto.PromotionProtobuf.Promotion parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gejian.pixel.proto.PromotionProtobuf.Promotion parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gejian.pixel.proto.PromotionProtobuf.Promotion parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gejian.pixel.proto.PromotionProtobuf.Promotion prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Promotion}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Promotion)
        com.gejian.pixel.proto.PromotionProtobuf.PromotionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gejian.pixel.proto.PromotionProtobuf.internal_static_Promotion_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gejian.pixel.proto.PromotionProtobuf.internal_static_Promotion_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gejian.pixel.proto.PromotionProtobuf.Promotion.class, com.gejian.pixel.proto.PromotionProtobuf.Promotion.Builder.class);
      }

      // Construct using com.gejian.pixel.proto.PromotionProtobuf.Promotion.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        title_ = "";

        key_ = "";

        type_ = 0;

        desc_ = "";

        compareType_ = 0;

        parameter_ = 0;

        precondition_ = 0;

        next_ = 0;

        award_ = "";

        percent_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gejian.pixel.proto.PromotionProtobuf.internal_static_Promotion_descriptor;
      }

      @java.lang.Override
      public com.gejian.pixel.proto.PromotionProtobuf.Promotion getDefaultInstanceForType() {
        return com.gejian.pixel.proto.PromotionProtobuf.Promotion.getDefaultInstance();
      }

      @java.lang.Override
      public com.gejian.pixel.proto.PromotionProtobuf.Promotion build() {
        com.gejian.pixel.proto.PromotionProtobuf.Promotion result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gejian.pixel.proto.PromotionProtobuf.Promotion buildPartial() {
        com.gejian.pixel.proto.PromotionProtobuf.Promotion result = new com.gejian.pixel.proto.PromotionProtobuf.Promotion(this);
        result.id_ = id_;
        result.title_ = title_;
        result.key_ = key_;
        result.type_ = type_;
        result.desc_ = desc_;
        result.compareType_ = compareType_;
        result.parameter_ = parameter_;
        result.precondition_ = precondition_;
        result.next_ = next_;
        result.award_ = award_;
        result.percent_ = percent_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gejian.pixel.proto.PromotionProtobuf.Promotion) {
          return mergeFrom((com.gejian.pixel.proto.PromotionProtobuf.Promotion)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gejian.pixel.proto.PromotionProtobuf.Promotion other) {
        if (other == com.gejian.pixel.proto.PromotionProtobuf.Promotion.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          onChanged();
        }
        if (other.getCompareType() != 0) {
          setCompareType(other.getCompareType());
        }
        if (other.getParameter() != 0) {
          setParameter(other.getParameter());
        }
        if (other.getPrecondition() != 0) {
          setPrecondition(other.getPrecondition());
        }
        if (other.getNext() != 0) {
          setNext(other.getNext());
        }
        if (!other.getAward().isEmpty()) {
          award_ = other.award_;
          onChanged();
        }
        if (!other.getPercent().isEmpty()) {
          percent_ = other.percent_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gejian.pixel.proto.PromotionProtobuf.Promotion parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gejian.pixel.proto.PromotionProtobuf.Promotion) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       **id
       * </pre>
       *
       * <code>uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       **id
       * </pre>
       *
       * <code>uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **id
       * </pre>
       *
       * <code>uint32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <pre>
       **标题
       * </pre>
       *
       * <code>string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **标题
       * </pre>
       *
       * <code>string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **标题
       * </pre>
       *
       * <code>string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **标题
       * </pre>
       *
       * <code>string title = 2;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **标题
       * </pre>
       *
       * <code>string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <pre>
       **关键字
       * </pre>
       *
       * <code>string key = 3;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **关键字
       * </pre>
       *
       * <code>string key = 3;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **关键字
       * </pre>
       *
       * <code>string key = 3;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **关键字
       * </pre>
       *
       * <code>string key = 3;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **关键字
       * </pre>
       *
       * <code>string key = 3;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       **类型
       * </pre>
       *
       * <code>uint32 type = 4;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       **类型
       * </pre>
       *
       * <code>uint32 type = 4;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **类型
       * </pre>
       *
       * <code>uint32 type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <pre>
       **desc
       * </pre>
       *
       * <code>string desc = 5;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **desc
       * </pre>
       *
       * <code>string desc = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **desc
       * </pre>
       *
       * <code>string desc = 5;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **desc
       * </pre>
       *
       * <code>string desc = 5;</code>
       */
      public Builder clearDesc() {
        
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **desc
       * </pre>
       *
       * <code>string desc = 5;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        desc_ = value;
        onChanged();
        return this;
      }

      private int compareType_ ;
      /**
       * <pre>
       **比较类型 &lt; &lt;= = &gt;= &gt; 从0开始
       * </pre>
       *
       * <code>uint32 compare_type = 6;</code>
       */
      public int getCompareType() {
        return compareType_;
      }
      /**
       * <pre>
       **比较类型 &lt; &lt;= = &gt;= &gt; 从0开始
       * </pre>
       *
       * <code>uint32 compare_type = 6;</code>
       */
      public Builder setCompareType(int value) {
        
        compareType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **比较类型 &lt; &lt;= = &gt;= &gt; 从0开始
       * </pre>
       *
       * <code>uint32 compare_type = 6;</code>
       */
      public Builder clearCompareType() {
        
        compareType_ = 0;
        onChanged();
        return this;
      }

      private int parameter_ ;
      /**
       * <pre>
       **参数
       * </pre>
       *
       * <code>uint32 parameter = 7;</code>
       */
      public int getParameter() {
        return parameter_;
      }
      /**
       * <pre>
       **参数
       * </pre>
       *
       * <code>uint32 parameter = 7;</code>
       */
      public Builder setParameter(int value) {
        
        parameter_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **参数
       * </pre>
       *
       * <code>uint32 parameter = 7;</code>
       */
      public Builder clearParameter() {
        
        parameter_ = 0;
        onChanged();
        return this;
      }

      private int precondition_ ;
      /**
       * <pre>
       **precondition
       * </pre>
       *
       * <code>uint32 precondition = 8;</code>
       */
      public int getPrecondition() {
        return precondition_;
      }
      /**
       * <pre>
       **precondition
       * </pre>
       *
       * <code>uint32 precondition = 8;</code>
       */
      public Builder setPrecondition(int value) {
        
        precondition_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **precondition
       * </pre>
       *
       * <code>uint32 precondition = 8;</code>
       */
      public Builder clearPrecondition() {
        
        precondition_ = 0;
        onChanged();
        return this;
      }

      private int next_ ;
      /**
       * <pre>
       **下一个任务
       * </pre>
       *
       * <code>uint32 next = 9;</code>
       */
      public int getNext() {
        return next_;
      }
      /**
       * <pre>
       **下一个任务
       * </pre>
       *
       * <code>uint32 next = 9;</code>
       */
      public Builder setNext(int value) {
        
        next_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **下一个任务
       * </pre>
       *
       * <code>uint32 next = 9;</code>
       */
      public Builder clearNext() {
        
        next_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object award_ = "";
      /**
       * <pre>
       **奖励
       * </pre>
       *
       * <code>string award = 10;</code>
       */
      public java.lang.String getAward() {
        java.lang.Object ref = award_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          award_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **奖励
       * </pre>
       *
       * <code>string award = 10;</code>
       */
      public com.google.protobuf.ByteString
          getAwardBytes() {
        java.lang.Object ref = award_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          award_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **奖励
       * </pre>
       *
       * <code>string award = 10;</code>
       */
      public Builder setAward(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        award_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **奖励
       * </pre>
       *
       * <code>string award = 10;</code>
       */
      public Builder clearAward() {
        
        award_ = getDefaultInstance().getAward();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **奖励
       * </pre>
       *
       * <code>string award = 10;</code>
       */
      public Builder setAwardBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        award_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object percent_ = "";
      /**
       * <pre>
       **进度
       * </pre>
       *
       * <code>string percent = 11;</code>
       */
      public java.lang.String getPercent() {
        java.lang.Object ref = percent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          percent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **进度
       * </pre>
       *
       * <code>string percent = 11;</code>
       */
      public com.google.protobuf.ByteString
          getPercentBytes() {
        java.lang.Object ref = percent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          percent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **进度
       * </pre>
       *
       * <code>string percent = 11;</code>
       */
      public Builder setPercent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        percent_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **进度
       * </pre>
       *
       * <code>string percent = 11;</code>
       */
      public Builder clearPercent() {
        
        percent_ = getDefaultInstance().getPercent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **进度
       * </pre>
       *
       * <code>string percent = 11;</code>
       */
      public Builder setPercentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        percent_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Promotion)
    }

    // @@protoc_insertion_point(class_scope:Promotion)
    private static final com.gejian.pixel.proto.PromotionProtobuf.Promotion DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gejian.pixel.proto.PromotionProtobuf.Promotion();
    }

    public static com.gejian.pixel.proto.PromotionProtobuf.Promotion getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Promotion>
        PARSER = new com.google.protobuf.AbstractParser<Promotion>() {
      @java.lang.Override
      public Promotion parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Promotion(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Promotion> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Promotion> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gejian.pixel.proto.PromotionProtobuf.Promotion getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Promotion_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Promotion_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Promotion.proto\"\274\001\n\tPromotion\022\n\n\002id\030\001 " +
      "\001(\r\022\r\n\005title\030\002 \001(\t\022\013\n\003key\030\003 \001(\t\022\014\n\004type\030" +
      "\004 \001(\r\022\014\n\004desc\030\005 \001(\t\022\024\n\014compare_type\030\006 \001(" +
      "\r\022\021\n\tparameter\030\007 \001(\r\022\024\n\014precondition\030\010 \001" +
      "(\r\022\014\n\004next\030\t \001(\r\022\r\n\005award\030\n \001(\t\022\017\n\007perce" +
      "nt\030\013 \001(\tB+\n\026com.gejian.pixel.protoB\021Prom" +
      "otionProtobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Promotion_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Promotion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Promotion_descriptor,
        new java.lang.String[] { "Id", "Title", "Key", "Type", "Desc", "CompareType", "Parameter", "Precondition", "Next", "Award", "Percent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
