// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Skill2.proto

package com.gejian.pixel.proto;

public final class Skill2Protobuf {
  private Skill2Protobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Skill2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Skill2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <pre>
     **id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     **name
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     **name
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     **icon
     * </pre>
     *
     * <code>string icon = 3;</code>
     */
    java.lang.String getIcon();
    /**
     * <pre>
     **icon
     * </pre>
     *
     * <code>string icon = 3;</code>
     */
    com.google.protobuf.ByteString
        getIconBytes();

    /**
     * <pre>
     **description
     * </pre>
     *
     * <code>string description = 4;</code>
     */
    java.lang.String getDescription();
    /**
     * <pre>
     **description
     * </pre>
     *
     * <code>string description = 4;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <pre>
     **priority
     * </pre>
     *
     * <code>string priority = 5;</code>
     */
    java.lang.String getPriority();
    /**
     * <pre>
     **priority
     * </pre>
     *
     * <code>string priority = 5;</code>
     */
    com.google.protobuf.ByteString
        getPriorityBytes();

    /**
     * <pre>
     **action
     * </pre>
     *
     * <code>string action = 6;</code>
     */
    java.lang.String getAction();
    /**
     * <pre>
     **action
     * </pre>
     *
     * <code>string action = 6;</code>
     */
    com.google.protobuf.ByteString
        getActionBytes();

    /**
     * <pre>
     **effect
     * </pre>
     *
     * <code>string effect = 7;</code>
     */
    java.lang.String getEffect();
    /**
     * <pre>
     **effect
     * </pre>
     *
     * <code>string effect = 7;</code>
     */
    com.google.protobuf.ByteString
        getEffectBytes();

    /**
     * <pre>
     **levels
     * </pre>
     *
     * <code>string levels = 8;</code>
     */
    java.lang.String getLevels();
    /**
     * <pre>
     **levels
     * </pre>
     *
     * <code>string levels = 8;</code>
     */
    com.google.protobuf.ByteString
        getLevelsBytes();

    /**
     * <pre>
     **logic
     * </pre>
     *
     * <code>string logic = 9;</code>
     */
    java.lang.String getLogic();
    /**
     * <pre>
     **logic
     * </pre>
     *
     * <code>string logic = 9;</code>
     */
    com.google.protobuf.ByteString
        getLogicBytes();
  }
  /**
   * Protobuf type {@code Skill2}
   */
  public  static final class Skill2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Skill2)
      Skill2OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Skill2.newBuilder() to construct.
    private Skill2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Skill2() {
      id_ = "";
      name_ = "";
      icon_ = "";
      description_ = "";
      priority_ = "";
      action_ = "";
      effect_ = "";
      levels_ = "";
      logic_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Skill2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              icon_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              priority_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              action_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              effect_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              levels_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              logic_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gejian.pixel.proto.Skill2Protobuf.internal_static_Skill2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gejian.pixel.proto.Skill2Protobuf.internal_static_Skill2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gejian.pixel.proto.Skill2Protobuf.Skill2.class, com.gejian.pixel.proto.Skill2Protobuf.Skill2.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <pre>
     **id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     **name
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **name
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ICON_FIELD_NUMBER = 3;
    private volatile java.lang.Object icon_;
    /**
     * <pre>
     **icon
     * </pre>
     *
     * <code>string icon = 3;</code>
     */
    public java.lang.String getIcon() {
      java.lang.Object ref = icon_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        icon_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **icon
     * </pre>
     *
     * <code>string icon = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIconBytes() {
      java.lang.Object ref = icon_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        icon_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 4;
    private volatile java.lang.Object description_;
    /**
     * <pre>
     **description
     * </pre>
     *
     * <code>string description = 4;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **description
     * </pre>
     *
     * <code>string description = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIORITY_FIELD_NUMBER = 5;
    private volatile java.lang.Object priority_;
    /**
     * <pre>
     **priority
     * </pre>
     *
     * <code>string priority = 5;</code>
     */
    public java.lang.String getPriority() {
      java.lang.Object ref = priority_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        priority_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **priority
     * </pre>
     *
     * <code>string priority = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPriorityBytes() {
      java.lang.Object ref = priority_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        priority_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTION_FIELD_NUMBER = 6;
    private volatile java.lang.Object action_;
    /**
     * <pre>
     **action
     * </pre>
     *
     * <code>string action = 6;</code>
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **action
     * </pre>
     *
     * <code>string action = 6;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EFFECT_FIELD_NUMBER = 7;
    private volatile java.lang.Object effect_;
    /**
     * <pre>
     **effect
     * </pre>
     *
     * <code>string effect = 7;</code>
     */
    public java.lang.String getEffect() {
      java.lang.Object ref = effect_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        effect_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **effect
     * </pre>
     *
     * <code>string effect = 7;</code>
     */
    public com.google.protobuf.ByteString
        getEffectBytes() {
      java.lang.Object ref = effect_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        effect_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVELS_FIELD_NUMBER = 8;
    private volatile java.lang.Object levels_;
    /**
     * <pre>
     **levels
     * </pre>
     *
     * <code>string levels = 8;</code>
     */
    public java.lang.String getLevels() {
      java.lang.Object ref = levels_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        levels_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **levels
     * </pre>
     *
     * <code>string levels = 8;</code>
     */
    public com.google.protobuf.ByteString
        getLevelsBytes() {
      java.lang.Object ref = levels_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        levels_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGIC_FIELD_NUMBER = 9;
    private volatile java.lang.Object logic_;
    /**
     * <pre>
     **logic
     * </pre>
     *
     * <code>string logic = 9;</code>
     */
    public java.lang.String getLogic() {
      java.lang.Object ref = logic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logic_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **logic
     * </pre>
     *
     * <code>string logic = 9;</code>
     */
    public com.google.protobuf.ByteString
        getLogicBytes() {
      java.lang.Object ref = logic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getIconBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, icon_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
      }
      if (!getPriorityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, priority_);
      }
      if (!getActionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, action_);
      }
      if (!getEffectBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, effect_);
      }
      if (!getLevelsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, levels_);
      }
      if (!getLogicBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, logic_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getIconBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, icon_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
      }
      if (!getPriorityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, priority_);
      }
      if (!getActionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, action_);
      }
      if (!getEffectBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, effect_);
      }
      if (!getLevelsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, levels_);
      }
      if (!getLogicBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, logic_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gejian.pixel.proto.Skill2Protobuf.Skill2)) {
        return super.equals(obj);
      }
      com.gejian.pixel.proto.Skill2Protobuf.Skill2 other = (com.gejian.pixel.proto.Skill2Protobuf.Skill2) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getIcon()
          .equals(other.getIcon());
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && getPriority()
          .equals(other.getPriority());
      result = result && getAction()
          .equals(other.getAction());
      result = result && getEffect()
          .equals(other.getEffect());
      result = result && getLevels()
          .equals(other.getLevels());
      result = result && getLogic()
          .equals(other.getLogic());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ICON_FIELD_NUMBER;
      hash = (53 * hash) + getIcon().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
      hash = (53 * hash) + getPriority().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      hash = (37 * hash) + EFFECT_FIELD_NUMBER;
      hash = (53 * hash) + getEffect().hashCode();
      hash = (37 * hash) + LEVELS_FIELD_NUMBER;
      hash = (53 * hash) + getLevels().hashCode();
      hash = (37 * hash) + LOGIC_FIELD_NUMBER;
      hash = (53 * hash) + getLogic().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gejian.pixel.proto.Skill2Protobuf.Skill2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gejian.pixel.proto.Skill2Protobuf.Skill2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gejian.pixel.proto.Skill2Protobuf.Skill2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gejian.pixel.proto.Skill2Protobuf.Skill2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gejian.pixel.proto.Skill2Protobuf.Skill2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gejian.pixel.proto.Skill2Protobuf.Skill2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gejian.pixel.proto.Skill2Protobuf.Skill2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gejian.pixel.proto.Skill2Protobuf.Skill2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gejian.pixel.proto.Skill2Protobuf.Skill2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gejian.pixel.proto.Skill2Protobuf.Skill2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gejian.pixel.proto.Skill2Protobuf.Skill2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gejian.pixel.proto.Skill2Protobuf.Skill2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gejian.pixel.proto.Skill2Protobuf.Skill2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Skill2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Skill2)
        com.gejian.pixel.proto.Skill2Protobuf.Skill2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gejian.pixel.proto.Skill2Protobuf.internal_static_Skill2_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gejian.pixel.proto.Skill2Protobuf.internal_static_Skill2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gejian.pixel.proto.Skill2Protobuf.Skill2.class, com.gejian.pixel.proto.Skill2Protobuf.Skill2.Builder.class);
      }

      // Construct using com.gejian.pixel.proto.Skill2Protobuf.Skill2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        name_ = "";

        icon_ = "";

        description_ = "";

        priority_ = "";

        action_ = "";

        effect_ = "";

        levels_ = "";

        logic_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gejian.pixel.proto.Skill2Protobuf.internal_static_Skill2_descriptor;
      }

      @java.lang.Override
      public com.gejian.pixel.proto.Skill2Protobuf.Skill2 getDefaultInstanceForType() {
        return com.gejian.pixel.proto.Skill2Protobuf.Skill2.getDefaultInstance();
      }

      @java.lang.Override
      public com.gejian.pixel.proto.Skill2Protobuf.Skill2 build() {
        com.gejian.pixel.proto.Skill2Protobuf.Skill2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gejian.pixel.proto.Skill2Protobuf.Skill2 buildPartial() {
        com.gejian.pixel.proto.Skill2Protobuf.Skill2 result = new com.gejian.pixel.proto.Skill2Protobuf.Skill2(this);
        result.id_ = id_;
        result.name_ = name_;
        result.icon_ = icon_;
        result.description_ = description_;
        result.priority_ = priority_;
        result.action_ = action_;
        result.effect_ = effect_;
        result.levels_ = levels_;
        result.logic_ = logic_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gejian.pixel.proto.Skill2Protobuf.Skill2) {
          return mergeFrom((com.gejian.pixel.proto.Skill2Protobuf.Skill2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gejian.pixel.proto.Skill2Protobuf.Skill2 other) {
        if (other == com.gejian.pixel.proto.Skill2Protobuf.Skill2.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getIcon().isEmpty()) {
          icon_ = other.icon_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (!other.getPriority().isEmpty()) {
          priority_ = other.priority_;
          onChanged();
        }
        if (!other.getAction().isEmpty()) {
          action_ = other.action_;
          onChanged();
        }
        if (!other.getEffect().isEmpty()) {
          effect_ = other.effect_;
          onChanged();
        }
        if (!other.getLevels().isEmpty()) {
          levels_ = other.levels_;
          onChanged();
        }
        if (!other.getLogic().isEmpty()) {
          logic_ = other.logic_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gejian.pixel.proto.Skill2Protobuf.Skill2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gejian.pixel.proto.Skill2Protobuf.Skill2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <pre>
       **id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       **name
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **name
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **name
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **name
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **name
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object icon_ = "";
      /**
       * <pre>
       **icon
       * </pre>
       *
       * <code>string icon = 3;</code>
       */
      public java.lang.String getIcon() {
        java.lang.Object ref = icon_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          icon_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **icon
       * </pre>
       *
       * <code>string icon = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIconBytes() {
        java.lang.Object ref = icon_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          icon_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **icon
       * </pre>
       *
       * <code>string icon = 3;</code>
       */
      public Builder setIcon(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        icon_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **icon
       * </pre>
       *
       * <code>string icon = 3;</code>
       */
      public Builder clearIcon() {
        
        icon_ = getDefaultInstance().getIcon();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **icon
       * </pre>
       *
       * <code>string icon = 3;</code>
       */
      public Builder setIconBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        icon_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <pre>
       **description
       * </pre>
       *
       * <code>string description = 4;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **description
       * </pre>
       *
       * <code>string description = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **description
       * </pre>
       *
       * <code>string description = 4;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **description
       * </pre>
       *
       * <code>string description = 4;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **description
       * </pre>
       *
       * <code>string description = 4;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object priority_ = "";
      /**
       * <pre>
       **priority
       * </pre>
       *
       * <code>string priority = 5;</code>
       */
      public java.lang.String getPriority() {
        java.lang.Object ref = priority_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          priority_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **priority
       * </pre>
       *
       * <code>string priority = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPriorityBytes() {
        java.lang.Object ref = priority_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          priority_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **priority
       * </pre>
       *
       * <code>string priority = 5;</code>
       */
      public Builder setPriority(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        priority_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **priority
       * </pre>
       *
       * <code>string priority = 5;</code>
       */
      public Builder clearPriority() {
        
        priority_ = getDefaultInstance().getPriority();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **priority
       * </pre>
       *
       * <code>string priority = 5;</code>
       */
      public Builder setPriorityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        priority_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object action_ = "";
      /**
       * <pre>
       **action
       * </pre>
       *
       * <code>string action = 6;</code>
       */
      public java.lang.String getAction() {
        java.lang.Object ref = action_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **action
       * </pre>
       *
       * <code>string action = 6;</code>
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        java.lang.Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **action
       * </pre>
       *
       * <code>string action = 6;</code>
       */
      public Builder setAction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **action
       * </pre>
       *
       * <code>string action = 6;</code>
       */
      public Builder clearAction() {
        
        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **action
       * </pre>
       *
       * <code>string action = 6;</code>
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        action_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object effect_ = "";
      /**
       * <pre>
       **effect
       * </pre>
       *
       * <code>string effect = 7;</code>
       */
      public java.lang.String getEffect() {
        java.lang.Object ref = effect_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          effect_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **effect
       * </pre>
       *
       * <code>string effect = 7;</code>
       */
      public com.google.protobuf.ByteString
          getEffectBytes() {
        java.lang.Object ref = effect_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          effect_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **effect
       * </pre>
       *
       * <code>string effect = 7;</code>
       */
      public Builder setEffect(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        effect_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **effect
       * </pre>
       *
       * <code>string effect = 7;</code>
       */
      public Builder clearEffect() {
        
        effect_ = getDefaultInstance().getEffect();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **effect
       * </pre>
       *
       * <code>string effect = 7;</code>
       */
      public Builder setEffectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        effect_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object levels_ = "";
      /**
       * <pre>
       **levels
       * </pre>
       *
       * <code>string levels = 8;</code>
       */
      public java.lang.String getLevels() {
        java.lang.Object ref = levels_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          levels_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **levels
       * </pre>
       *
       * <code>string levels = 8;</code>
       */
      public com.google.protobuf.ByteString
          getLevelsBytes() {
        java.lang.Object ref = levels_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          levels_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **levels
       * </pre>
       *
       * <code>string levels = 8;</code>
       */
      public Builder setLevels(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        levels_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **levels
       * </pre>
       *
       * <code>string levels = 8;</code>
       */
      public Builder clearLevels() {
        
        levels_ = getDefaultInstance().getLevels();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **levels
       * </pre>
       *
       * <code>string levels = 8;</code>
       */
      public Builder setLevelsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        levels_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object logic_ = "";
      /**
       * <pre>
       **logic
       * </pre>
       *
       * <code>string logic = 9;</code>
       */
      public java.lang.String getLogic() {
        java.lang.Object ref = logic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          logic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **logic
       * </pre>
       *
       * <code>string logic = 9;</code>
       */
      public com.google.protobuf.ByteString
          getLogicBytes() {
        java.lang.Object ref = logic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **logic
       * </pre>
       *
       * <code>string logic = 9;</code>
       */
      public Builder setLogic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        logic_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **logic
       * </pre>
       *
       * <code>string logic = 9;</code>
       */
      public Builder clearLogic() {
        
        logic_ = getDefaultInstance().getLogic();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **logic
       * </pre>
       *
       * <code>string logic = 9;</code>
       */
      public Builder setLogicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        logic_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Skill2)
    }

    // @@protoc_insertion_point(class_scope:Skill2)
    private static final com.gejian.pixel.proto.Skill2Protobuf.Skill2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gejian.pixel.proto.Skill2Protobuf.Skill2();
    }

    public static com.gejian.pixel.proto.Skill2Protobuf.Skill2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Skill2>
        PARSER = new com.google.protobuf.AbstractParser<Skill2>() {
      @java.lang.Override
      public Skill2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Skill2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Skill2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Skill2> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gejian.pixel.proto.Skill2Protobuf.Skill2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Skill2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Skill2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Skill2.proto\"\226\001\n\006Skill2\022\n\n\002id\030\001 \001(\t\022\014\n" +
      "\004name\030\002 \001(\t\022\014\n\004icon\030\003 \001(\t\022\023\n\013description" +
      "\030\004 \001(\t\022\020\n\010priority\030\005 \001(\t\022\016\n\006action\030\006 \001(\t" +
      "\022\016\n\006effect\030\007 \001(\t\022\016\n\006levels\030\010 \001(\t\022\r\n\005logi" +
      "c\030\t \001(\tB(\n\026com.gejian.pixel.protoB\016Skill" +
      "2Protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Skill2_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Skill2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Skill2_descriptor,
        new java.lang.String[] { "Id", "Name", "Icon", "Description", "Priority", "Action", "Effect", "Levels", "Logic", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
