# Netty 服务配置 (自定义端口)
socket:
  netty:
    port: 19999
    debug: true

# 数据库配置
dbConfig:
  # 用户名
  username: ${DB_USERNAME:root}
  # 密码
  password: ${DB_PASSWORD:%Fv3oSK8mzonBP^k}
  # 主机
  host: ${DB_HOST:110.40.133.131}
  # 端口
  port: ${DB_PORT:13306}
  # 数据库名称
  dbname: ${DB_DBNAME:ourgame}


cors:
  allowedOrigins: "*"
  allowedMethods: GET,POST,PUT,DELETE,HEAD,PATCH,OPTIONS
  allowCredentials: true
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${dbConfig.username}
    password: ${dbConfig.password}
    url: jdbc:mysql://${dbConfig.host}:${dbConfig.port}/${dbConfig.dbname}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 120000
      maximum-pool-size: 15
      minimum-idle: 5
      read-only: false
      connection-test-query: SELECT 1
  redis:
    host: ${REDIS_HOST:110.40.133.131}
    port: ${REDIS_PORT:16379}
    password: ${REDIS_PASSWORD:2JIY3SsfTNr8}
    database: ${REDIS_DATABASE:1}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  security:
    user:
      name: admin
      password: Gejian@2021
  session:
    timeout: 30m

# mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

config-url:
  MACOSX-IAP-VERIFY-URL: https://sandbox.itunes.apple.com/verifyReceipt
  CENTOS-IAP-VERIFY-URL: https://buy.itunes.apple.com/verifyReceipt
