package com.gejian.pixel.constants;

/**
 * @author ZhouQiang
 * @date 2021/8/30$
 */
public interface CommandConstants {

	String LOGIN_REQUEST = "COMM_LOGIN_REQUEST";

	String LOGIN_RESPONSE = "COMM_LOGIN_RESPONSE";
	String SET_NICKNAME = "COMM_SET_NICKNAME_REQUEST";
	String PING = "COMM_PING_REQUEST";
	String BUY_HERO = "COMM_BUY_HERO_REQUEST";
	String UPDATE_HERO_FORMATION = "COMM_UPDATE_HERO_FORMATION_REQUEST";
	String LET_HERO_CONSUME_EXP_BOOK = "COMM_LET_HERO_CONSUME_EXP_BOOK_REQUEST";
	String UNLOCK_HERO_SKILL = "COMM_UNLOCK_HERO_SKILL_REQUEST";
	String UPGRADE_HERO_SKILL_LEVEL = "COMM_UPGRADE_HERO_SKILL_LEVEL_REQUEST";
	String HERO_UPGRADE_STAR = "COMM_HERO_UPGRADE_STAR_REQUEST";
	String DAILY_CHECKIN = "COMM_DAILY_CHECKIN_REQUEST";
	String STAGE_PASSED = "COMM_STAGE_PASSED_REQUEST";
	String HERO_UPGRADE_QUALITY = "COMM_HERO_UPGRADE_QUALITY_REQUEST";
	String GET_PVP_VICTORY_AWARD = "COMM_GET_PVP_VICTORY_AWARD_REQUEST";
	String PURCHASE_VERIFY = "COMM_PURCHASE_VERIFY_REQUEST";
	String ENTER_DUNGEON = "COMM_ENTER_DUNGEON_REQUEST";
	String UPDATE_TEMPORARY_BACKPACK = "COMM_UPDATE_TEMPORARY_BACKPACK_REQUEST";
	String HARVEST_TEMPORARY_BACKPACK = "COMM_HARVEST_TEMPORARY_BACKPACK_REQUEST";
	String UPGRADE_TEMPORARY_BACKPACK = "COMM_UPGRADE_TEMPORARY_BACKPACK_REQUEST";
	String RANKLIST = "COMM_RANKLIST_REQUEST";
	String RANKLIST_RELATIVE_POWER = "COMM_RANKLIST_RELATIVE_POWER_REQUEST";
	String REFRESH_STORE = "COMM_REFRESH_STORE_REQUEST";
	String BUY_STORE_ITEM_HELPER = "COMM_BUY_STORE_ITEM_REQUEST_HELPER";
	String BUY_STORE_ITEM = "COMM_BUY_STORE_ITEM_REQUEST";
	String DISMISS_HERO = "COMM_DISMISS_HERO_REQUEST";
	String GET_PVP_DATA = "COMM_GET_PVP_DATA_REQUEST";
	String GET_GIFTBAG_LIST = "COMM_GET_GIFTBAG_LIST_REQUEST";
	String OPEN_GIFTBAG = "COMM_OPEN_GIFTBAG_REQUEST";
	String COMPOUND_HERO = "COMM_COMPOUND_HERO_REQUEST";
	String QUERY_BUY_HERO_PRICE = "COMM_QUERY_BUY_HERO_PRICE_REQUEST";
	String CHAT_MESSAGE = "COMM_CHAT_MESSAGE";
	String GET_PROMOTION_AWARD = "COMM_GET_PROMOTION_AWARD_REQUEST";
	String COMBINE_ITEM = "COMM_COMBINE_ITEM_REQUEST";
	String REDUCE_STONE = "COMM_REDUCE_STONE_REQUEST";
	String UPDATE_BINDING_ACCOUNT = "COMM_UPDATE_BINDING_ACCOUNT_REQUEST";
}
