package com.gejian.pixel.enums;

/**
 * @author ljb
 * @date 2021年08月31日 11:27
 * @description 错误枚举
 */
public interface ErrorEnum {
	int ERROR_SUCCESS = 0;
	int ERROR_CAN_NOT_CHANGE_NICKNAME = 1;
	int ERROR_CAN_NOT_DISMISS_HERO_IN_FORMATION = 2;
	int ERROR_EXCEED_DAILY_LIMIT = 3;
	int ERROR_EXP_BOOK_NOT_EXIST = 4;
	int ERROR_HERO_ALREADY_EXISTS = 5;
	int ERROR_HERO_LEVEL_NOT_EQUAL_99 = 6;
	int ERROR_HERO_NOT_FOUND = 7;
	int ERROR_IAP_NETWORK_ERROR = 8;
	int ERROR_IAP_RECEIPT_JSON_ERROR = 9;
	int ERROR_INVALID_BUY_HERO_TYPE = 10;
	int ERROR_INVALID_IAP_RECEIPT_BID_OR_UNIQUE_VENDOR_IDENTIFIER_MISMATCH = 11;
	int ERROR_INVALID_IAP_RECEIPT_PRODUCT_ID = 12;
	int ERROR_INVALID_IAP_RECEIPT_QUANTITY = 13;
	int ERROR_INVALID_IAP_RECEIPT_TRANSACTION_ID = 14;
	int ERROR_INVALID_IAP_RECEIPT_USED = 15;
	int ERROR_INVALID_NICKNAME = 16;
	int ERROR_INVALID_PARAMETER_EXCHANGE_TYPE_ERROR = 17;
	int ERROR_INVALID_PARAMETER_GIFTBAG_ACTION = 18;
	int ERROR_INVALID_PARAMETER_REFRESH_STORE_TYPE = 19;
	int ERROR_INVALID_PARAMETER_STORE_ITEM = 20;
	int ERROR_INVALID_STAGE = 21;
	int ERROR_INVALID_TEAM_SIZE = 22;
	int ERROR_NICKNAME_ALREADY_EXISTS = 23;
	int ERROR_NOT_COOLDOWN = 24;
	int ERROR_NOT_ENOUGH_GOLD = 25;
	int ERROR_NOT_ENOUGH_HERO_QUALITY = 26;
	int ERROR_NOT_ENOUGH_PVP_TIMES = 27;
	int ERROR_NOT_ENOUGH_RESOURCES = 28;
	int ERROR_NOT_ENOUGH_STONE = 29;
	int ERROR_NOT_ENTER_DUNGEON_YET = 30;
	int ERROR_OBJECT_NOT_FOUND = 31;
	int ERROR_OPERATION_PENDING = 32;
	int ERROR_PLAYER_NOT_FOUND = 33;
	int ERROR_REACH_LIMIT = 34;
	int ERROR_REACH_QUALITY_LIMIT = 35;
	int ERROR_SKILL_ALREADY_UNLOCK = 36;
	int ERROR_SKILL_NOT_FOUND = 37;
	int ERROR_SKILL_NOT_UNLOCK_YET = 38;
	int ERROR_INVALID_PARAMETER = 39;
	int ERROR_TODAY_ALREADY_CHECK_IN = 40;
	int ERROR_UNKNOW_IAP_RECEIPT_UNKNOW_PRODUCT_ID = 41;
	int ERROR_UNKNOW_SKILL = 42;
	int ERROR_BANNED = 43;
	int ERROR_NOT_LOGIN_YET = 44;
	int ERROR_SESSION_EXPIRED = 45;
	int ERROR_STORE_ALREADY_REFRESHED = 46;
	int ERROR_ARCHIVE_NOT_EXIST = 47;
	int ERROR_PROMOTION_NOT_EXIST = 48;
	int ERROR_PROMOTION_ALREADY_FINISHED = 49;
	int ERROR_CLIENT_VERSION_TOOOOO_OLD = 50;
	int ERROR_PROMOTION_NOT_FINISHED = 51;
	int ERROR_NOT_ENOUGH_HONOR = 52;
}